title: "Fundamentos de Telecomunicaciones"
description: "Andy Nirvan Hernández x Guzmán"


url: "http://webjeda.com" 
permalink: /:title/ 


compress_html:
  clippings: 
    - html
    - div
    - p
    - ul
    - td
    - h1
    - h2
    - h3
    - h4
    - link
    - meta
    - footer
    - nav
    - img
    - header
    - hr
    - br
    - head
    - style
    - li
    - ol
    - time
    - main
    - script
    - title
  comments: ["<!-- ", " -->"] 
  endings: [all]              
  ignore:
    envs: [local]             
  blanklines: false         
  profile: false              
  startings: []               


analytics: UA-83979019-1


color-1: '#e74c3c'   
color-2: '#1abc9c'   
color-3: '#3498db'   
color-4: '#f39c12'   
color-5: '#9b59b6'   
color-6: '#2ecc71'   
color-7: '#e67e22'   
color-8: '#34495e'   
